Week 2 - Initial Functionality
SiftingSands/DeepBass pull request #3
Opened 2018-09-18 16:39 UTC by SiftingSands

Demonstrate read and write capability with simple song cross fading. Four example tracks are included with linear and sigmoid transitions.

2018-09-20 21:24 UTC, mrunfeldt requested changes
You probably don't want to use to use MEL spectrogram. Other than that, LGTM (looks good to me)

2018-09-20 21:24 UTC, mrunfeldt commented on src/analysis/explore.py
> +# Calculate Mel Spectrogram
MEL is optimized for human language. My concern here is that you are going to lose valuable spectral information from the music. I recommend just using a regular FFT to create your spectrograms and not do any initial filtering (like MEL) before hand. You can look at the data across a few songs to define the spectral range (min and max) and resolution (bin size)

2018-09-20 21:24 UTC, mrunfeldt commented on src/analysis/explore.py
> +hop_length = 512
It's good to get in the habit of defining all of your parameters at the top/beginning of your code. If you have time later, you can then pass them with a param file or as a command input.

2018-09-20 21:24 UTC, mrunfeldt commented on src/model/crossfade_simple.py
> +    raise ValueError('Sampling rates between songs must be identical')
Error catching, nice!

2018-09-20 21:24 UTC, mrunfeldt commented on src/model/crossfade_simple.py
> +    raise ValueError('Sampling rates between songs must be identical')
If you have time, you might want to make a function to check sampling rate before you even load the songs. Not a big priority right now, though

2018-09-26 20:29 UTC, mrunfeldt approved these changes

2018-09-26 20:34 UTC, mrunfeldt commented on src/notebooks/nsynth_interpolation.py
> +    fadein = (0.5 * (1.0 - np.cos(3.1415 * np.arange(length) /
math.pi

2018-09-26 20:45 UTC, SiftingSands commented on src/notebooks/nsynth_interpolation.py
> +    fadein = (0.5 * (1.0 - np.cos(3.1415 * np.arange(length) /
Got it!

2018-09-26 20:46 UTC, merged